"""
Resume text extraction that keeps hyperlinks.

Most resumes hide their URLs behind words: "GitHub", "Portfolio", "[Code: GitHub Repo]",
"[View Badge]". The visible text says "GitHub Repo"; the actual URL lives in a PDF link
annotation. Plain text extraction drops the annotation, so a tailored resume rebuilt from
that text ends up with dead "GitHub Repo" labels that link nowhere (a real bug reported
by a user).

This module reads both: the characters (pdfplumber) and the link annotations, finds which
words sit under each link's rectangle, and rewrites the text so every link is VISIBLE:
"[Code: GitHub Repo]" -> "Code: github.com/user/repo". Visible URLs are also what ATS
parsers expect — they read text, not annotations.

Credential links (Credly badges, "View Certificate") are dropped from the text along with
their anchor: the certification name stays, the badge link goes. Those verification
pages can't be checked or regenerated by Pathlight, and recruiters don't need them on a
one-page resume.
"""
import io
import re
from dataclasses import asdict, dataclass

import pdfplumber
from pdfplumber.utils import extract_text as chars_to_text

CREDENTIAL_HOSTS = (
    "credly.com", "youracclaim.com", "accredible.com", "scrimba.com/certificate",
    "coursera.org/verify", "coursera.org/account/accomplishments", "udemy.com/certificate",
    "ude.my/", "credential.net", "certificates.", "verify.", "badgr.", "learn.microsoft.com/api/credentials",
    "freecodecamp.org/certification", "hackerrank.com/certificates", "nptel.ac.in", "skillshare.com/certificates",
)
CREDENTIAL_ANCHOR = re.compile(r"\b(badge|certificate|certification|credential|verify|verification)\b", re.I)


@dataclass
class ResumeLink:
    anchor: str
    url: str
    kind: str  # contact | credential | web

    def as_dict(self) -> dict:
        return asdict(self)


def display_url(url: str) -> str:
    """https://www.github.com/user/ -> github.com/user (what goes on the page)."""
    if url.lower().startswith("mailto:"):
        return url[7:]
    if url.lower().startswith("tel:"):
        return url[4:]
    shown = re.sub(r"^https?://", "", url.strip(), flags=re.I)
    shown = re.sub(r"^www\.", "", shown, flags=re.I)
    return shown.rstrip("/")


def classify(anchor: str, url: str) -> str:
    low = url.lower()
    if low.startswith(("mailto:", "tel:")):
        return "contact"
    if any(h in low for h in CREDENTIAL_HOSTS) or CREDENTIAL_ANCHOR.search(anchor or ""):
        return "credential"
    return "web"


def _looks_like_url(text: str) -> bool:
    return bool(re.fullmatch(r"\S+\.\S+", text.strip())) and " " not in text.strip()


def _anchor_for(page, link: dict) -> str:
    # A character belongs to a link when its midpoint is inside the link rectangle.
    # (pdfplumber's within_bbox needs the whole glyph inside, which misses most anchors.)
    chars = [
        c for c in page.chars
        if link["x0"] - 1 <= (c["x0"] + c["x1"]) / 2 <= link["x1"] + 1
        and link["top"] - 2 <= (c["top"] + c["bottom"]) / 2 <= link["bottom"] + 2
    ]
    return chars_to_text(chars, x_tolerance=1.5).strip()


def extract_pdf(raw: bytes) -> tuple[str | None, list[ResumeLink]]:
    """Returns (text, links) with every link anchor resolved in the text. Never raises —
    a corrupt/scanned PDF returns (None, [])."""
    try:
        pages_text: list[str] = []
        links: list[ResumeLink] = []
        with pdfplumber.open(io.BytesIO(raw)) as pdf:
            for page in pdf.pages:
                pages_text.append(page.extract_text(x_tolerance=1.5) or "")
                for link in sorted(page.hyperlinks, key=lambda h: (round(h["top"]), h["x0"])):
                    url = (link.get("uri") or "").strip()
                    if not url:
                        continue
                    anchor = _anchor_for(page, link)
                    links.append(ResumeLink(anchor=anchor, url=url, kind=classify(anchor, url)))
        text = "\n".join(pages_text).strip()
        if not text:
            return None, []
        return resolve_links(reflow(text), links), links
    except Exception:
        return None, []


# "[Code: GitHub Repo]" / "(Link)" style wrappers around an anchor.
_WRAPPED = r"[\[\(]\s*(?P<label>[A-Za-z ]{{0,20}}?)\s*:?\s*{anchor}\s*[\]\)]"


def resolve_links(text: str, links: list[ResumeLink]) -> str:
    """Rewrites anchors in reading order so each link's URL is visible (or, for
    credentials, removed). Each link consumes the FIRST unresolved occurrence of its
    anchor after the previous link's position, so three "GitHub Repo" anchors map to
    their three different repos."""
    cursor = 0
    for link in links:
        anchor = link.anchor
        if not anchor:
            continue
        flexible = r"\s*".join(re.escape(part) for part in anchor.split())
        wrapped = re.compile(_WRAPPED.format(anchor=flexible))
        bare = re.compile(rf"(?<![A-Za-z0-9./]){flexible}(?![A-Za-z0-9])")

        match = wrapped.search(text, cursor) or bare.search(text, cursor)
        if match is None:
            continue
        is_wrapped = match.re is wrapped

        if link.kind == "credential":
            replacement = ""
        elif link.kind == "contact" or _looks_like_url(anchor):
            # Already visible (an email, a phone number, or a URL written out).
            replacement = display_url(link.url) if is_wrapped else match.group(0)
        else:
            shown = display_url(link.url)
            label = (match.group("label") or "").strip() if is_wrapped else ""
            replacement = f"{label}: {shown}" if label else shown

        # Keep the next word from gluing onto the URL ("...pathlight]Tech:" -> "... | Tech:").
        rest = text[match.end():]
        nxt = rest.lstrip(" \t")[:1]
        if replacement and nxt and nxt not in "\n|,;.)":
            replacement += " | "
            rest = rest.lstrip(" \t")
        text = text[: match.start()] + replacement + rest
        cursor = match.start() + len(replacement)

    # Tidy what credential removal leaves behind.
    text = re.sub(r"[ \t]*\|[ \t]*(?=\n|$)", "", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    return text


def visible_urls(text: str) -> list[str]:
    """Web addresses written out in resume text (used to check the tailor kept them)."""
    pattern = r"(?<![@\w])(?:https?://)?(?:www\.)?(?:[a-z0-9-]+\.)+[a-z]{2,}(?:/[^\s|,;)\]]*)?"
    found = []
    for m in re.finditer(pattern, text or "", flags=re.I):
        candidate = m.group(0).rstrip(".")
        if "/" in candidate or candidate.lower().startswith(("http", "www.")):
            found.append(display_url(candidate))
    return list(dict.fromkeys(found))


_BULLET_START = re.compile(r"^\s*[-•*▪●◦·]\s+")
# "Core Competencies: ..." — a skills-category line, never a wrapped continuation.
_LABEL_START = re.compile(r"^[A-Z][A-Za-z/&()+.\- ]{1,32}:\s")


def reflow(text: str) -> str:
    """Joins lines the PDF wrapped mid-sentence ("...experience (Spring" + "Boot, React")
    back into one logical line, so each bullet is one line for the tailor, the diff and
    the PDF renderer. A line is a continuation when the line above it (as printed) ran
    close to the full text width and this line doesn't start a bullet or a heading."""
    from app.core.resume_pdf import is_heading  # local: resume_pdf imports nothing from here

    lines = [l.rstrip() for l in text.split("\n")]
    # Typical full-line width: the 90th percentile, so one unusually long line (often a
    # contact line) doesn't make every normal line look short.
    lengths = sorted(len(l) for l in lines if l.strip())
    widest = lengths[int(len(lengths) * 0.9) - 1] if lengths else 0
    out: list[str] = []
    prev_raw = ""
    for line in lines:
        stripped = line.strip()
        continuation = (
            out
            and stripped
            and len(prev_raw) >= widest * 0.8
            and not _BULLET_START.match(line)
            and not is_heading(stripped)
            and not prev_raw.endswith(":")
            and not _LABEL_START.match(stripped)
        )
        if continuation:
            out[-1] = out[-1] + " " + stripped
        else:
            out.append(line)
        prev_raw = line
    return "\n".join(out)


# "[View Badge]", "[Code: GitHub Repo]", "(Link)" — link labels whose URL is unknown.
_DEAD_ANCHOR = re.compile(
    r"\s*[\[\(]\s*(?:[A-Za-z ]{0,12}:\s*)?(?:view\s+)?(?:badge|certificate|credential|verify|link|live(?:\s+demo)?|demo|"
    r"github(?:\s+repo)?|repo(?:sitory)?|code|project|website|portfolio)\s*[\]\)]",
    re.I,
)


def drop_dead_anchors(text: str) -> str:
    """For resumes whose original file (and so its links) is no longer available:
    removes bracketed link labels that would otherwise print as text pointing nowhere."""
    cleaned = _DEAD_ANCHOR.sub(" ", text or "")
    cleaned = re.sub(r"^(\s*[-•*▪●◦·])\s*", r"\1 ", cleaned, flags=re.M)  # "•Tech" -> "• Tech"
    return re.sub(r"[ \t]+(?=\n|$)", "", cleaned)
